language: python
install: "sudo apt-get install -y libgeoip-dev python-dev && pip install -r requirements.txt && pip install -r dev-requirements.txt"
env:
  - TOX_ENV=flake8
  - TOX_ENV=twisted-debian-squeeze
  - TOX_ENV=twisted-debian-wheezy
  - TOX_ENV=twisted-latest-12
  - TOX_ENV=twisted-latest-13
  - TOX_ENV=twisted-latest-14
  - TOX_ENV=twisted-latest-15
  - TOX_ENV=pypy

script:
  - tox -c tox.ini -e $TOX_ENV

after_success:
  - coveralls
  - codecov
