language: python
sudo: required
dist: precise

install: "sudo apt-get update && sudo apt-get install -y libgeoip-dev python-dev && pip install -r requirements.txt && pip install -r dev-requirements.txt"
env:
  - TOX_ENV=twisted-latest-15
  - TOX_ENV=twisted-latest-16
  - TOX_ENV=py35
  - TOX_ENV=pypy

script:
  - tox -c tox.ini -e $TOX_ENV

after_success:
  - coveralls
  - codecov
