language: python
sudo: required

install: "sudo apt-get update && sudo apt-get install -y libgeoip-dev python-dev && pip install --upgrade pip && pip install tox"

# just listing everything in the matrix, because:
# - anything else apparently failed
# - this is what klein does

matrix:
  include:
# these two are "special", we only run them in "a really new python"
  - python: "3.6"
    env: TOX_ENV=flake8
  - python: "3.6"
    env: TOX_ENV=readme_render

# for every python we support; we're currently testing on Twisted 16,
# 17, 18 and 19

# python 3.6

  - python: "3.6"
    env: TOX_ENV=py36-tx16
  - python: "3.6"
    env: TOX_ENV=py36-tx17
  - python: "3.6"
    env: TOX_ENV=py36-tx18
  - python: "3.6"
    env: TOX_ENV=py36-tx19

# python 3.4 (twisted dropped support in tx19, so ... should we?)
# https://twistedmatrix.com/trac/ticket/9613

  - python: "3.4"
    env: TOX_ENV=py34-tx16
  - python: "3.4"
    env: TOX_ENV=py34-tx17
  - python: "3.4"
    env: TOX_ENV=py34-tx18
#  - python: "3.4"
#    env: TOX_ENV=py34-tx19

# python 2.7

  - python: "2.7"
    env: TOX_ENV=py27-tx16
  - python: "2.7"
    env: TOX_ENV=py27-tx17
  - python: "2.7"
    env: TOX_ENV=py27-tx18
  - python: "2.7"
    env: TOX_ENV=py27-tx19

# PyPy

  - python: "pypy"
    env: TOX_ENV=pypy-tx16
  - python: "pypy"
    env: TOX_ENV=pypy-tx17
  - python: "pypy"
    env: TOX_ENV=pypy-tx18
  - python: "pypy"
    env: TOX_ENV=pypy-tx19

script:
  - apt-cache policy libssl-dev
  - tox -c tox.ini -e $TOX_ENV

after_success:
  - coveralls
  - codecov
